global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rentease-spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 🌟 正确：穿透回物理机 IDEA