server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # 上报给同网络下的 Loki

scrape_configs:
  - job_name: rentease-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: au-rentease-backend
          __path__: /var/log/app/*.log # 监控这个目录下所有以 .log 结尾的文件